# Generated by Django 4.2.2 on 2023-07-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tag_task_delete_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='observation',
            field=models.TextField(default='Sin comentarios'),
            preserve_default=False,
        ),
    ]
