# Generated by Django 4.2.2 on 2023-07-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='priority',
            field=models.CharField(max_length=100),
        ),
    ]
